Replace JS with MDX Doc
creativecommons/fonts pull request #28
Opened 2020-03-29 13:10 UTC by megha070

## Fixes

Fixes #25  by @megha070 

## Description

## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-03-29 13:23 UTC, megha070 commented
![image](https://user-images.githubusercontent.com/40516822/77850207-7d814380-71ee-11ea-8219-2a70ed110962.png)
@dhruvkb can you please help me with this error.

2020-03-29 17:23 UTC, dhruvkb commented
@megha070 this occurs if you call a function within the same function, like a recursion without an exit condition.

2020-03-29 19:12 UTC, megha070 commented
@dhruvkb the decorators are the same for all the fonts except for the font-family, so as to remove repetitive code, I tried importing decorator by defining it in another function but the contents are not visible. Could you please tell the reason behind this anomaly? 
This code is working fine as of now but why can't we import a decorator?

2020-03-30 00:15 UTC, dhruvkb commented
You should ideally not import content from other stories. If two stories need some feature, add it to `helpers.js`.

2020-03-30 01:02 UTC, dhruvkb requested changes
I've updated the **Source Sans Pro** story to indicate my expectations from an MDX perspective. Would be awesome if you could make the corresponding updates in the **Accidenz Commons** and **Roboto Condensed** stories.

2020-03-30 03:35 UTC, megha070 commented
@dhruvkb I couldn't think of using typeset in this. I would be extremely thankful if you could please direct me to some source that could help me with various components offered by @storybook/addon-blocks and their use-cases.
Also, I wanted to inquire if I need to submit a separate PR for the other two fonts or make required changes in this itself.

2020-03-30 03:47 UTC, megha070 commented
@dhruvkb Don't we have to include the sample text?

2020-03-30 05:56 UTC, dhruvkb commented
That's the problem with Storybooks, it changes so quickly that all documentation quickly becomes very old. The best source of info on Storybooks is the code itself.

So if you go searching in
```
node_modules/@storybook/components/dist/blocks/index.d.ts
``` 
you'll find all the blocks they support.

2020-03-30 05:59 UTC, megha070 commented
I see. Thanks a ton, will go through this once.

2020-03-30 06:03 UTC, dhruvkb requested changes
You cannot simply copy from Source Sans Pro to the other two files as they do not have the weights 600 and 700.

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/roboto_condensed.stories.mdx
> +  sampleText=". ? ! ' & : ; @ # < > ( ) { } [ ]" />
There are no semibold and bold variants in Roboto. Did you not see the `roboto_condensed.scss` file?

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/roboto_condensed.stories.mdx
> +It is used in Vocabulary in 3 font weights: regular (400), semibold (600) and bold (700).
No. Just one: 400.

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/roboto_condensed.stories.mdx
> +Roboto,a neo-grotesque sans-serif typeface family developed by Google,was designed by Christian Robertson.
```suggestion
Roboto, a neo-grotesque sans-serif typeface family developed by Google, was designed by Christian Robertson. 
```

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/roboto_condensed.stories.mdx
> +It is a sans serif condensed typeface which is the default font on Android.
```suggestion
It is a sans-serif, condensed typeface which is the default font on Android.
```

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/accidenz_commons.stories.mdx
> +It is used in Vocabulary in 3 font weights: regular (400), semibold (600) and bold (700).
Just one: 400.

2020-03-30 06:03 UTC, dhruvkb commented on src/stories/accidenz_commons.stories.mdx
> +  sampleText=". ? ! ' & : ; @ # < > ( ) { } [ ]" />
These variants do not exist. See `accidenz_commons.scss`.

2020-03-30 06:06 UTC, megha070 commented on src/stories/roboto_condensed.stories.mdx
> +  sampleText=". ? ! ' & : ; @ # < > ( ) { } [ ]" />
Oh I am sorry, will make necessary changes

2020-03-31 04:21 UTC, dhruvkb approved these changes
LGTM 🚀

2020-03-31 05:43 UTC, merged