Move cc icons to the right code point
creativecommons/fonts pull request #93
Opened 2020-06-12 17:47 UTC by Tanuj22

## Fixes

Fixes #92 by @dhruvkb 

## Description
Move cc icons to the right code point
## Technical details

## Tests

## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-06-12 17:51 UTC, Tanuj22 commented
![Screenshot from 2020-06-12 23-18-33](https://user-images.githubusercontent.com/42486853/84532003-19f1b700-ad03-11ea-9c04-7dfd8233e6db.png)
The CC part isn't true now. Should I change or remove it?

2020-06-12 17:54 UTC, dhruvkb commented
@Tanuj22 update it.

2020-06-12 17:59 UTC, Tanuj22 commented
@dhruvkb Update it to `\ec** & \1f1**`?

2020-06-12 18:07 UTC, dhruvkb requested changes
[You missed CC-ND](https://www.ctrl.blog/entry/creative-commons-unicode-fallback-font.html). Once you add it, you can classify them into standard and non-standard categories in the code-points table.

2020-06-12 22:15 UTC, Tanuj22 commented
![Screenshot from 2020-06-13 03-42-01](https://user-images.githubusercontent.com/42486853/84550375-0dcc2080-ad28-11ea-96ae-a2ef85e9f4d3.png)
@dhruvkb Please check this out. Although `CC-ND (229c)` doesn't fit in any of them

2020-06-13 08:53 UTC, dhruvkb requested changes
Almost ready!

2020-06-13 08:53 UTC, dhruvkb commented on src/styles/vocabulary_icons.scss
> -  "cc-logo": "\ec00",
Please also arrange them in order of code point, separating the standard from the non-standard with a blank line.

2020-06-13 08:58 UTC, dhruvkb commented
Just put CC-ND with CC Standard and change the table column to `1f1**` + `229c`. Actually the already existing [Circled Equals](https://www.fileformat.info/info/unicode/char/229c/index.htm) sign was so similar to CC-ND, I think they just repurposed it.

2020-06-13 11:35 UTC, dhruvkb approved these changes

2020-06-13 11:57 UTC, merged

2020-06-13 12:04 UTC, Dishebh commented on src/stories/vocabulary_icons.stories.mdx
> +The CC standard icons include those that have been added to the Unicode Standard in version 13.0. Do note the the CC-ND
`Do not the the` -> `Do not that the`, I guess :sweat_smile: